import type { Config } from "tailwindcss";
import { addDynamicIconSelectors } from "@iconify/tailwind";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "icon-[bi--check2-circle]",
    "icon-[tabler--automation]",
    "icon-[tabler--users]",
    "icon-[tabler--book]",
    "icon-[tabler--chart-bar]",
    "icon-[tabler--map-pin]",
    "icon-[tabler--shopping-cart]",
    "icon-[tabler--server]",
    "icon-[tabler--chart-line]",
    "icon-[tabler--test-pipe]",
    "icon-[tabler--forms]",
    "icon-[tabler--brand-html5]",
    "icon-[tabler--robot]",
    "icon-[tabler--cloud-upload]",
    "icon-[tabler--chart-pie]",
    "icon-[tabler--building-warehouse]",
    "icon-[tabler--cash]",
    "icon-[tabler--shield-check]",
    "icon-[tabler--cloud-off]",
    "icon-[tabler--refresh]",
    // Hero animated icons
    "icon-[tabler--code]",
    "icon-[devicon--typescript]",
    "icon-[devicon--postgresql]",
    "icon-[devicon--docker]",
    "icon-[simple-icons--sanity]",
    // Project card icons
    "icon-[tabler--user-code]",
    "icon-[material-symbols--arrow-outward-rounded]",
    // About section
    "icon-[tabler--rocket]",
    "icon-[tabler--chart-line]",
    "icon-[tabler--brand-github]",
    "icon-[tabler--coffee]",
    "icon-[tabler--world]",
    "icon-[tabler--clock]",
    "icon-[tabler--map-pin]",
    // Experience section
    "icon-[simple-icons--movistar]",
    "icon-[tabler--plane]",
    "icon-[tabler--code-dots]",
    "icon-[tabler--building]",
    "icon-[tabler--tree]",
    "icon-[tabler--briefcase]",
    "icon-[tabler--calendar]",
    "icon-[tabler--device-laptop]",
    // Skills section
    "icon-[devicon--tailwindcss]",
    "icon-[devicon--html5]",
    "icon-[devicon--css3]",
    "icon-[devicon--python]",
    "icon-[devicon--git]",
    "icon-[devicon--jest]",
    "icon-[logos--graphql]",
    // AI & Productivity
    "icon-[tabler--cursor-text]",
    "icon-[simple-icons--anthropic]",
    "icon-[simple-icons--n8n]",
    "icon-[tabler--plug-connected]",
    "icon-[tabler--brain]",
    "icon-[tabler--sparkles]",
    // Backend / DevOps
    "icon-[devicon--dotnetcore]",
    "icon-[devicon--kubernetes]",
    "icon-[devicon--githubactions]",
    // Data & QA
    "icon-[devicon--mysql]",
    "icon-[simple-icons--oracle]",
    "icon-[simple-icons--playwright]",
    "icon-[simple-icons--vitest]",
    "icon-[simple-icons--sonarqube]",
    "icon-[tabler--target]",
    "icon-[tabler--database]",
    "icon-[tabler--layout]",
    "icon-[tabler--layout-grid]",
    // Header
    "icon-[tabler--language]",
    "icon-[tabler--message-circle]",
    "icon-[tabler--chevron-down]",
    "icon-[tabler--x]",
    "icon-[tabler--folder]",
    "icon-[tabler--pencil]",
    "icon-[tabler--arrow-right]",
    // Footer
    "icon-[tabler--mail]",
    "icon-[tabler--phone]",
    "icon-[tabler--brand-linkedin]",
    "icon-[tabler--brand-whatsapp]",
    "icon-[tabler--heart-filled]",
    // Mind CTA
    "icon-[tabler--message-circle-2]",
    "icon-[tabler--shield-check]",
    // AppBar / Projects
    "icon-[tabler--chevron-right]",
    "icon-[tabler--layers-subtract]",
    "icon-[tabler--browser]",
    // Workflow page
    "icon-[tabler--sparkles]",
    "icon-[simple-icons--nextdotjs]",
    "icon-[simple-icons--springboot]",
  ],
  theme: {
    extend: {
      colors: {
        "jojanes-green": "#2ae98d",
        "jojanes-green-glow": "#1a6b44",
        "jojanes-green-light": "#4ff5b0",
        "jojanes-subtitle": "#8c8c94",
        "jojanes-black": "#0A0C0B",
        "jojanes-dark": "#111312",
        "jojanes-surface": "#111312",
        "jojanes-gray": "#1d1d1d",
        "jojanes-gray-dark": "#1E1E1E",
        "jojanes-white": "#F0F2F1",
        "jojanes-white-muted": "#6B7B72",
        "jojanes-gray-light": "#A0A0A0",
        "jojanes-border": "#2a2d2b",
        "jojanes-green-dark": "#229C70",
        "jojanes-red": "#FF4C4C",
        "jojanes-blue": "#3B82F6",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [addDynamicIconSelectors(), require("tailwindcss-animate")],
};
export default config;
